# Generated by Django 4.2.7 on 2024-08-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_item',
            old_name='item_name',
            new_name='name',
        ),
    ]
